version: '3'
services:
  medusa:
    restart: always
    image: linuxserver/medusa
    container_name: medusa
    networks:
      - common
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/medusa:/config
      - ./data/media/tv:/tv
      - ./data/downloads/finished:/downloads
    ports:
      - 8081:8081 
    restart: unless-stopped

  radarr:
    restart: always
    image: linuxserver/radarr
    container_name: radarr
    networks:
      - common
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/radarr:/config
      - ./data/media/movies:/movies
      - ./data/downloads/finished:/downloads
    ports:
      - 7878:7878 
    restart: unless-stopped
  lazylibrarian:
    image: thraxis/lazylibrarian-calibre
    restart: always
    container_name: lazylibrarian
    networks:
      - common
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/lazylibrarian:/config
      - ./data/downloads/finished:/downloads
      - ./data/media/books:/books
      - ./data/media/audiobooks:/audiobooks
      - ./data/media/magazines:/magazines
      - ./data/media/comics:/comics
    ports:
      - 5299:5299 
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    restart: always
    container_name: lidarr
    networks:
      - common
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/lidarr:/config
      - ./data/media/music:/music
      - ./data/downloads/finished:/downloads
    ports:
      - 8686:8686 
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    restart: always
    container_name: jackett
    networks:
      - common
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/jackett:/config
      - ./data/downloads/finished:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  nextcloud:
    container_name: nextcloud 
    image: nextcloud:latest
    restart: always
    expose:
      - '80'
    networks:
      - common
    volumes:
      - ./data/media/nextcloud/:/data/
    env_file:
      - .env_nextcloud
      - .env_general
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - .env_general
    networks:
      - common 
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx
    depends_on: 
      - onlyoffice-document-server
    image: nginx
    restart: always
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - common 
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certs:/etc/certs
      - ./web:/var/www/html
    env_file:
      - .env_general
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  transmission:
    image: linuxserver/transmission
    restart: always
    container_name: transmission
    networks:
      - common
    env_file:
      - .env_general
    volumes:
      - ./data/transmission/config:/config
      - ./data/downloads:/downloads
    restart: unless-stopped

  homeassistant: 
    image: homeassistant/home-assistant
    restart: always
    container_name: homeassistant
    volumes:
      - ./data/homeassistant/config:/config
    networks:
      - common

networks:
  common: 
    driver: 'bridge'
  
volumes:
  document_data:
  document_log:
  mysql_data:
  nextcloud_data:
